// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_XCap4UkxK8L-FewTOqfPynkvza6wCg',
    appId: '1:892920104114:web:7cfe00ae8ba00fd52e75ab',
    messagingSenderId: '892920104114',
    projectId: 'e-commerce-app-3ac76',
    authDomain: 'e-commerce-app-3ac76.firebaseapp.com',
    storageBucket: 'e-commerce-app-3ac76.firebasestorage.app',
    measurementId: 'G-SSW7R0EJ7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnAfhAuWk_5uGAkshVFsjq_XxUdqn7Rjo',
    appId: '1:892920104114:android:c5b251f453989fb42e75ab',
    messagingSenderId: '892920104114',
    projectId: 'e-commerce-app-3ac76',
    storageBucket: 'e-commerce-app-3ac76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHurs0cazoE1OsJxGeLNkbzlyLp7R2b1Q',
    appId: '1:892920104114:ios:7a59cdc852c568e22e75ab',
    messagingSenderId: '892920104114',
    projectId: 'e-commerce-app-3ac76',
    storageBucket: 'e-commerce-app-3ac76.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHurs0cazoE1OsJxGeLNkbzlyLp7R2b1Q',
    appId: '1:892920104114:ios:7a59cdc852c568e22e75ab',
    messagingSenderId: '892920104114',
    projectId: 'e-commerce-app-3ac76',
    storageBucket: 'e-commerce-app-3ac76.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt_XCap4UkxK8L-FewTOqfPynkvza6wCg',
    appId: '1:892920104114:web:8d42afea6ea805272e75ab',
    messagingSenderId: '892920104114',
    projectId: 'e-commerce-app-3ac76',
    authDomain: 'e-commerce-app-3ac76.firebaseapp.com',
    storageBucket: 'e-commerce-app-3ac76.firebasestorage.app',
    measurementId: 'G-J30Y9JSMQF',
  );
}
